# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0546a3f72ee2bede2a72b9ffb667236295f44101853c5836c2c3aa75527fbad754bb420d01da88db765d4a6285b3732350587890429c7c316f81bd864c66767c

test:
  secret_key_base: 24fdb826313457719ae2a4c1d34060201d7abcea2d2fddfd0e37e5d010df095983c4b499955c721a3b5f966fe886c7dd894743ced3d5bdc7892b883dd9811cd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: b36456e96db257f78cb7d1ecd2d47de295185a170b1060539df04a93756e501eff0bec33a3058b8a0341af6a69298e793fabc639de4bf73f817145567d13250a
